language: cpp
compiler: gcc
addons:
  apt:
    packages:
      - cmake
      - lcov

script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test

after_success:
  - lcov -c --directory . --output-file coverage.info
  - lcov -r coverage.info '/usr/include/*' '*/gtest/*' '*external/*' -o coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

